services:
  postgresqldb:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example # postgres/example
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/script/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgresqldata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgresqldata:
