/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AppUser } from '../model';
/**
 * AppUserSelfServiceApiControllerApi - axios parameter creator
 * @export
 */
export const AppUserSelfServiceApiControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/selfServiceApi/getAppUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AppUser} appUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppUser: async (appUser: AppUser, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appUser' is not null or undefined
            assertParamExists('updateAppUser', 'appUser', appUser)
            const localVarPath = `/selfServiceApi/updateAppUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(appUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppUserSelfServiceApiControllerApi - functional programming interface
 * @export
 */
export const AppUserSelfServiceApiControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppUserSelfServiceApiControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAppUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAppUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppUserSelfServiceApiControllerApi.getAppUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {AppUser} appUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAppUser(appUser: AppUser, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppUser(appUser, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppUserSelfServiceApiControllerApi.updateAppUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppUserSelfServiceApiControllerApi - factory interface
 * @export
 */
export const AppUserSelfServiceApiControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppUserSelfServiceApiControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppUser(options?: RawAxiosRequestConfig): AxiosPromise<AppUser> {
            return localVarFp.getAppUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AppUser} appUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppUser(appUser: AppUser, options?: RawAxiosRequestConfig): AxiosPromise<AppUser> {
            return localVarFp.updateAppUser(appUser, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppUserSelfServiceApiControllerApi - object-oriented interface
 * @export
 * @class AppUserSelfServiceApiControllerApi
 * @extends {BaseAPI}
 */
export class AppUserSelfServiceApiControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppUserSelfServiceApiControllerApi
     */
    public getAppUser(options?: RawAxiosRequestConfig) {
        return AppUserSelfServiceApiControllerApiFp(this.configuration).getAppUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AppUser} appUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppUserSelfServiceApiControllerApi
     */
    public updateAppUser(appUser: AppUser, options?: RawAxiosRequestConfig) {
        return AppUserSelfServiceApiControllerApiFp(this.configuration).updateAppUser(appUser, options).then((request) => request(this.axios, this.basePath));
    }
}

