/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppUser
 */
export interface AppUser {
    /**
     * 
     * @type {number}
     * @memberof AppUser
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppUser
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'lastModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUser
     */
    'lastModifiedBy'?: string;
}

