/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppUserRole
 */
export interface AppUserRole {
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'userRole'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'appClientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'lastModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserRole
     */
    'lastModifiedBy'?: string;
}

