/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisteredClientResponse
 */
export interface RegisteredClientResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'clientIdIssuedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'clientSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'clientSecretExpiresAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredClientResponse
     */
    'clientName'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof RegisteredClientResponse
     */
    'clientAuthenticationMethods'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof RegisteredClientResponse
     */
    'authorizationGrantTypes'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof RegisteredClientResponse
     */
    'redirectUris'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof RegisteredClientResponse
     */
    'scopes'?: Set<string>;
}

